# Generated by Django 4.2.6 on 2023-10-26 22:26

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('0', 'Default'), ('1', 'email')], default='0')),
                ('format', models.CharField(choices=[('pop', 'Pop'), ('banner', 'Banner'), ('redirect', 'Redirect')])),
                ('link', models.CharField(max_length=250)),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')])),
                ('os', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')])),
                ('geo', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_budget', models.IntegerField(null=True)),
                ('start_after_moderation', models.BooleanField(default=False)),
                ('moderation_passed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
    ]
