# Generated by Django 4.2.6 on 2023-10-29 14:32

from django.db import migrations, models
import platform_main.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', platform_main.models.user.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
