# Generated by Django 4.2.6 on 2023-11-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0005_campaign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='geo',
            field=models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States')]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='os',
            field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'IOS')]),
        ),
    ]
