# Generated by Django 4.2.6 on 2023-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0006_alter_campaign_geo_alter_campaign_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped'),
        ),
    ]
