# Generated by Django 4.2.6 on 2023-11-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0008_alter_campaign_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='next_status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('edited', 'Edited')], default='stopped'),
        ),
    ]
