# Generated by Django 4.2.6 on 2023-11-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0009_campaign_next_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='start_after_moderation',
        ),
    ]
