# Generated by Django 4.2.6 on 2023-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0010_remove_campaign_start_after_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='moderation_passed',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current_status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='next_status',
            field=models.CharField(choices=[('stop_requested', 'Stop requested'), ('run_requested', 'Run requested')], null=True),
        ),
    ]
