# Generated by Django 4.2.6 on 2023-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0011_remove_campaign_moderation_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='next_status',
            field=models.CharField(choices=[('stop_requested', 'Stop requested'), ('run_requested', 'Run requested'), ('edit_requested', 'Edit requested')], null=True),
        ),
    ]
