# Generated by Django 4.2.6 on 2023-11-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0012_user_name_alter_campaign_next_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
