# Generated by Django 4.2.6 on 2023-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0013_campaign_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
