# Generated by Django 4.2.6 on 2023-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0014_user_company_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
