# Generated by Django 4.2.6 on 2023-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0015_user_is_stopped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='next_status',
            field=models.CharField(choices=[('stop_requested', 'Stop requested'), ('run_requested', 'Run requested')], null=True),
        ),
    ]
