# Generated by Django 4.2.6 on 2023-12-15 13:53

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0016_alter_campaign_next_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
        migrations.AddField(
            model_name='campaign',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='platform_main.source'),
            preserve_default=False,
        ),
    ]
