# Generated by Django 4.2.6 on 2023-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0017_source_campaign_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='source',
        ),
        migrations.AddField(
            model_name='campaign',
            name='source',
            field=models.ManyToManyField(to='platform_main.source'),
        ),
    ]
