# Generated by Django 4.2.6 on 2023-12-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0018_remove_campaign_source_campaign_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='source',
            new_name='sources',
        ),
    ]
