# Generated by Django 4.2.6 on 2023-12-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0019_rename_source_campaign_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='sources',
        ),
        migrations.AddField(
            model_name='campaign',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='platform_main.source'),
            preserve_default=False,
        ),
    ]
