# Generated by Django 4.2.6 on 2023-12-25 22:27

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0020_remove_campaign_sources_campaign_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePrice',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('0', 'Default'), ('1', 'email')], default='0')),
                ('format', models.CharField(choices=[('pop', 'Pop'), ('banner', 'Banner'), ('redirect', 'Redirect')])),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')])),
                ('os', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'IOS')])),
                ('geo', models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_main.source')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.TimestampMixin),
        ),
    ]
