# Generated by Django 4.2.6 on 2024-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0021_sourceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_zero_balance',
            field=models.BooleanField(default=False),
        ),
    ]
