# Generated by Django 4.2.6 on 2024-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0022_user_allow_zero_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
