# Generated by Django 4.2.6 on 2024-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0023_alter_user_company_alter_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='system_title',
            field=models.CharField(default='system-name', max_length=20),
            preserve_default=False,
        ),
    ]
