# Generated by Django 4.2.6 on 2024-01-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0024_source_system_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='system_title',
            new_name='system_id',
        ),
    ]
