# Generated by Django 4.2.6 on 2024-01-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0026_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('0', 'No email'), ('1', 'Email')], default='0'),
        ),
        migrations.AlterField(
            model_name='sourceprice',
            name='type',
            field=models.CharField(choices=[('0', 'No email'), ('1', 'Email')], default='0'),
        ),
    ]
