# Generated by Django 4.2.6 on 2024-01-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0027_alter_campaign_type_alter_sourceprice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicks',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='platform_main.campaign'),
        ),
    ]
