# Generated by Django 4.2.6 on 2024-02-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0029_alter_campaign_os_alter_sourceprice_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='price',
        ),
        migrations.AlterField(
            model_name='source',
            name='system_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sourceprice',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_main.source'),
        ),
    ]
