# Generated by Django 4.2.6 on 2024-02-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0030_remove_source_price_alter_source_system_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceprice',
            name='os',
        ),
    ]
