# Generated by Django 4.2.6 on 2024-02-19 18:51

from django.db import migrations, models
import platform_main.models.campaign


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0031_remove_sourceprice_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='os',
            field=platform_main.models.campaign.ChoiceArrayField(base_field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'MacOS'), ('android', 'Android'), ('ios', 'IOS')], max_length=20), size=None),
        ),
    ]
