# Generated by Django 4.2.6 on 2024-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0032_alter_campaign_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceprice',
            name='type',
            field=models.CharField(choices=[('0', 'No email'), ('1', 'Email')]),
        ),
    ]
