# Generated by Django 4.2.6 on 2024-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0033_alter_sourceprice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('0', 'No email'), ('1', 'Email')]),
        ),
    ]
