# Generated by Django 4.2.6 on 2024-02-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0034_alter_campaign_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='daily_budget',
        ),
        migrations.AddField(
            model_name='campaign',
            name='clicks_per_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
