# Generated by Django 4.2.6 on 2024-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0037_invoice_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
