# Generated by Django 4.2.6 on 2024-03-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_main', '0040_alter_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
